### PR TITLE
fix: check if matchPath is defined

### LINKED ISSUE #14: `TypeError: matchPath is not a function`
I get this error with the latest update (`1.4.0`). I wasn't having any issue with the previous version (`1.3.2`).

Log: https://github.com/RebeccaStevens/is-immutable-type/actions/runs/4072123978/jobs/7014570183
PR that generated log: https://github.com/RebeccaStevens/is-immutable-type/pull/38

### PR DESCRIPTION
**Pull request by luanglopes**
fix #14

### CODE REVIEW

File: resolverFactory.js [hunk 1]
```diff
@@ -4,14 +4,12 @@ import { matchPath } from './matchPath.js'
 
 export const resolverFactory = (resolveTs) => {
     return function (specifier, ctx, defaultResolve) {
-        let match
+        let match = matchPath && matchPath(specifier)
```
Comment (RebeccaStevens) [inline resolverFactory.js:7]: `const` should be used here rather than `let`.

Comment (luanglopes) [reply resolverFactory.js:7]: Actually not, because it could change line 12
